/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yeespec_libuvccamera_uvccamera_glutils_JniUtils */

#ifndef _Included_com_yeespec_libuvccamera_uvccamera_glutils_JniUtils
#define _Included_com_yeespec_libuvccamera_uvccamera_glutils_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yeespec_libuvccamera_uvccamera_glutils_JniUtils
 * Method:    getFreShnesFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yeespec_libuvccamera_uvccamera_glutils_JniUtils_getFreShnesFormC
        (JNIEnv *, jclass);
JNIEXPORT jstring JNICALL Java_com_yeespec_libuvccamera_uvccamera_glutils_JniUtils_getBitmapGamma
        (JNIEnv *, jclass);
JNIEXPORT jstring JNICALL Java_com_yeespec_libuvccamera_uvccamera_glutils_JniUtils_getOperationBrignes
        (JNIEnv *, jclass);
JNIEXPORT jstring JNICALL Java_com_yeespec_libuvccamera_uvccamera_glutils_JniUtils_getFreshnes_AVG
        (JNIEnv *, jclass);
JNIEXPORT jstring JNICALL Java_com_yeespec_libuvccamera_uvccamera_glutils_JniUtils_changeBrightness
        (JNIEnv *, jclass);
JNIEXPORT jstring JNICALL Java_com_yeespec_libuvccamera_uvccamera_glutils_JniUtils_fillOnePixelBitmap
        (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
